# Generated by Django 5.2.7 on 2025-10-27 22:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('label', models.CharField(max_length=40, unique=True)),
                ('state', models.CharField(default='DRAFT', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RemittanceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('stored_path', models.TextField()),
                ('status', models.CharField(choices=[('STAGED', 'STAGED'), ('PARSED', 'PARSED'), ('FAILED', 'FAILED'), ('DUPLICATE', 'DUPLICATE')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StagedClaims',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='remittances.financeperiod')),
            ],
        ),
        migrations.CreateModel(
            name='ClientRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=160)),
                ('norm_name', models.CharField(db_index=True, max_length=160)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remittances.program')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=160)),
                ('check_date', models.DateField()),
                ('check_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client_name', models.CharField(max_length=160)),
                ('hcpcs_cpt', models.CharField(max_length=16)),
                ('units', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('billed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_date', models.DateField()),
                ('meta', models.JSONField(default=dict)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remittances.financeperiod')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='remittances.program')),
            ],
        ),
    ]
